CREATE TABLE RENTALS 
(
Id int IDENTITY (1,1) PRIMARY KEY NOT NULL,
CarId int NOT NULL,
CustomerId int NOT NULL,
RentDate DATETIME NOT NULL DEFAULT(GETDATE()),
ReturnDate DATETIME DEFAULT(GETDATE()),
CONSTRAINT FORCustomerId FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS(ID),
CONSTRAINT FkCarId FOREIGN KEY (CarId) REFERENCES USERS(ID)
);